### ISSUE TITLE
GET /users/{userID}

### ISSUE THREAD

**Issue by michaelknoch** [locator-kn/cor#33]
add following attributes to response:
- number of followers
- number of locations
- hometown

fix imagepath, api/v1 -> api/v2

**Comment by timoweiss** [comment]
@markusheilig @michaelknoch we can add these properties by default if you want.
we could also add these properties only if requested, eg:
- GET /users/{userId}?count=followers,locations
- GET /users/{userId}?followers=true&locations=true

property hometown is already provided but its named `residence` (it might be most of the time an empty string since almost no one added this information).

**Comment by michaelknoch** [comment]
d'accord with the extra request :+1:

**Comment by timoweiss** [comment]
done, valid options:
- /users/{userId}?count=followers,locations
- /users/{userId}?count=locations,followers
- /users/{userId}?count=followers
- /users/{userId}?count=locations

**Comment by timoweiss** [comment]
`fix imagepath, api/v1 -> api/v2` will be fixed with new migration. not sure when we do that.
